### ISSUE TITLE
Use COPY instead of ADD in Dockerfile

### ISSUE THREAD

**Issue by Redlinkk** [Manu-Tran/blogRecettes#1]
According to the [CIS Docker Benchmark](https://success.docker.com/api/asset/.%2Frefarch%2Fsecurity-best-practices%2FCIS_Docker_Benchmark_v1.2.0.pdf) (page 136), COPY should be used instead of ADD whenever possible.

The offending line is here: https://github.com/Manu-Tran/blogRecettes/blob/b454f5fb601c4474f1ee5124821086ac044257b4/webhook-handler/Dockerfile#L8

**Comment by Manu-Tran** [comment]
Thank you very much for taking the time to raise this issue.
Please find the fix in this commit : https://github.com/Manu-Tran/blogRecettes/commit/6b58621b846eaff2597f8e318db64253106fc382
