### ISSUE TITLE
'articles' should not always be plural

### ISSUE THREAD

**Issue by Redlinkk** [Manu-Tran/blogRecettes#3]
https://github.com/Manu-Tran/blogRecettes/blob/5656f1d9b3085246d39275e2163835b5e40a815f/pelican/custom-templates/index.html#L100

A test is required here, to know if the singular or plural form is needed

**Comment by Manu-Tran** [comment]
Thank you very much for taking the time to raise this issue.
Please find the fix in this commit : https://github.com/Manu-Tran/blogRecettes/commit/a709ba12b78509d73ed077b3ec5da7dab3db7941
